version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - .data/app/static:/app/static
      - .data/app/media:/app/media
    env_file: ./root/.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./root/.env
