version: '3.9'

services:
  root:
    container_name: root
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./root:/root
      - ./data/app/static:/data/app/static
      - ./data/app/media:/data/app/media
    env_file: ./root/.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./root/.env
